-- 0019_kama_es_esp_series.sql
-- Seeds KAMA ES/ESP Series variants. Product kama-serie-es-esp already exists with no variants.
-- 6 variants: ES6/ES7/ES8 (cargo van, unitized body) + ESP6/ESP7/ESP8 (passenger van)
-- All BEV. Wheelbase 3050–3450mm. GVW 3050–3350kg. Motor 35/70kW.
-- ES models: GOTION battery 41.932kWh / 332.8V / 220km range.
-- ESP models: CATL dual-pack 41.86–53.58kWh / 334.88V / dual range.

UPDATE products
SET
  variants = '[
    {
      "model": "ES6",
      "fuel_type": "electric",
      "emission": null,
      "payload_t": 1.5,
      "cabin": "unitized body",
      "wheelbase_mm": 3050,
      "overall_dims": "4865x1715x2065",
      "cargo_box": "2805x1550x1350 (6m³)",
      "curb_weight_kg": 1600,
      "gvw_kg": 3050,
      "max_speed_kmh": 90,
      "tyre": "185R14LT",
      "front_rear_overhang_mm": "750/1065",
      "wheel_track_mm": "1460/1450",
      "final_ratio": null,
      "qty_wheels": "4+1",
      "brake_system": "Hydraulic brake",
      "parking_brake": "Front disc/rear drum",
      "gearshift": null,
      "battery_volt": null,
      "engine": null,
      "battery_ev": {
        "voltage_v": 332.8,
        "battery_brand": "GOTION",
        "battery_type": "Lithium Iron Phosphate",
        "pack_kwh": 41.932,
        "charger": "Fast/slow",
        "motor_brand": "Wuhan Lincontrol",
        "rated_peak_kw": "35/70",
        "range_km": 220
      },
      "features": {
        "abs": true,
        "power_steering": true,
        "ac": true,
        "power_window": true,
        "central_lock": true,
        "media": "MP5"
      }
    },
    {
      "model": "ESP6",
      "fuel_type": "electric",
      "emission": null,
      "payload_t": 1.0,
      "cabin": "unitized body",
      "wheelbase_mm": 3050,
      "overall_dims": "4865x1715x2065",
      "cargo_box": "Seats: 2+3+3+3",
      "curb_weight_kg": 1730,
      "gvw_kg": 3050,
      "max_speed_kmh": 90,
      "tyre": "185R14LT",
      "front_rear_overhang_mm": "750/1065",
      "wheel_track_mm": "1460/1450",
      "final_ratio": null,
      "qty_wheels": "4+1",
      "brake_system": "Hydraulic brake",
      "parking_brake": "Front disc/rear drum",
      "gearshift": null,
      "battery_volt": null,
      "engine": null,
      "battery_ev": {
        "voltage_v": 334.88,
        "battery_brand": "CATL",
        "battery_type": "Lithium Iron Phosphate",
        "pack_kwh": 53.58,
        "charger": "Fast/slow",
        "motor_brand": "Wuhan Lincontrol",
        "rated_peak_kw": "35/70",
        "range_km": 280
      },
      "features": {
        "abs": true,
        "power_steering": true,
        "ac": true,
        "power_window": true,
        "central_lock": true,
        "media": "MP5"
      },
      "notes": "Furgón de pasajeros. Dos configuraciones de batería: 41.86 kWh / 225 km y 53.58 kWh / 280 km"
    },
    {
      "model": "ES7",
      "fuel_type": "electric",
      "emission": null,
      "payload_t": 1.5,
      "cabin": "unitized body",
      "wheelbase_mm": 3450,
      "overall_dims": "5265x1715x2065",
      "cargo_box": "3205x1550x1350 (7m³)",
      "curb_weight_kg": 1630,
      "gvw_kg": 3150,
      "max_speed_kmh": 90,
      "tyre": "185R14LT",
      "front_rear_overhang_mm": "750/1065",
      "wheel_track_mm": "1460/1450",
      "final_ratio": null,
      "qty_wheels": "4+1",
      "brake_system": "Hydraulic brake",
      "parking_brake": "Front disc/rear drum",
      "gearshift": null,
      "battery_volt": null,
      "engine": null,
      "battery_ev": {
        "voltage_v": 332.8,
        "battery_brand": "GOTION",
        "battery_type": "Lithium Iron Phosphate",
        "pack_kwh": 41.932,
        "charger": "Fast/slow",
        "motor_brand": "Wuhan Lincontrol",
        "rated_peak_kw": "35/70",
        "range_km": 220
      },
      "features": {
        "abs": true,
        "power_steering": true,
        "ac": true,
        "power_window": true,
        "central_lock": true,
        "media": "MP5"
      }
    },
    {
      "model": "ESP7",
      "fuel_type": "electric",
      "emission": null,
      "payload_t": 1.0,
      "cabin": "unitized body",
      "wheelbase_mm": 3450,
      "overall_dims": "5265x1715x2065",
      "cargo_box": "Seats: 2+3+3+3+3",
      "curb_weight_kg": 1750,
      "gvw_kg": 3150,
      "max_speed_kmh": 90,
      "tyre": "185R14LT",
      "front_rear_overhang_mm": "750/1065",
      "wheel_track_mm": "1460/1450",
      "final_ratio": null,
      "qty_wheels": "4+1",
      "brake_system": "Hydraulic brake",
      "parking_brake": "Front disc/rear drum",
      "gearshift": null,
      "battery_volt": null,
      "engine": null,
      "battery_ev": {
        "voltage_v": 334.88,
        "battery_brand": "CATL",
        "battery_type": "Lithium Iron Phosphate",
        "pack_kwh": 53.58,
        "charger": "Fast/slow",
        "motor_brand": "Wuhan Lincontrol",
        "rated_peak_kw": "35/70",
        "range_km": 280
      },
      "features": {
        "abs": true,
        "power_steering": true,
        "ac": true,
        "power_window": true,
        "central_lock": true,
        "media": "MP5"
      },
      "notes": "Furgón de pasajeros. Dos configuraciones de batería: 41.86 kWh / 220 km y 53.58 kWh / 280 km"
    },
    {
      "model": "ES8",
      "fuel_type": "electric",
      "emission": null,
      "payload_t": 1.2,
      "cabin": "unitized body",
      "wheelbase_mm": 3450,
      "overall_dims": "5265x1870x2060",
      "cargo_box": "3225x1705x1380 (8m³)",
      "curb_weight_kg": 1760,
      "gvw_kg": 3350,
      "max_speed_kmh": 90,
      "tyre": "195/70R15LT",
      "front_rear_overhang_mm": "750/1065",
      "wheel_track_mm": "1615/1605",
      "final_ratio": null,
      "qty_wheels": "4+1",
      "brake_system": "Hydraulic brake",
      "parking_brake": "Front disc/rear drum",
      "gearshift": null,
      "battery_volt": null,
      "engine": null,
      "battery_ev": {
        "voltage_v": 332.8,
        "battery_brand": "GOTION",
        "battery_type": "Lithium Iron Phosphate",
        "pack_kwh": 41.932,
        "charger": "Fast/slow",
        "motor_brand": "Wuhan Lincontrol",
        "rated_peak_kw": "35/70",
        "range_km": 200
      },
      "features": {
        "abs": true,
        "power_steering": true,
        "ac": true,
        "power_window": true,
        "central_lock": true,
        "media": "MP5"
      }
    },
    {
      "model": "ESP8",
      "fuel_type": "electric",
      "emission": null,
      "payload_t": 1.0,
      "cabin": "unitized body",
      "wheelbase_mm": 3450,
      "overall_dims": "5265x1870x2060",
      "cargo_box": "Seats: 2+4+4+4",
      "curb_weight_kg": 1800,
      "gvw_kg": 3350,
      "max_speed_kmh": 90,
      "tyre": "195/70R15LT",
      "front_rear_overhang_mm": "750/1065",
      "wheel_track_mm": "1615/1605",
      "final_ratio": null,
      "qty_wheels": "4+1",
      "brake_system": "Hydraulic brake",
      "parking_brake": "Front disc/rear drum",
      "gearshift": null,
      "battery_volt": null,
      "engine": null,
      "battery_ev": {
        "voltage_v": 334.88,
        "battery_brand": "CATL",
        "battery_type": "Lithium Iron Phosphate",
        "pack_kwh": 53.58,
        "charger": "Fast/slow",
        "motor_brand": "Wuhan Lincontrol",
        "rated_peak_kw": "35/70",
        "range_km": 260
      },
      "features": {
        "abs": true,
        "power_steering": true,
        "ac": true,
        "power_window": true,
        "central_lock": true,
        "media": "MP5"
      },
      "notes": "Furgón de pasajeros. Dos configuraciones de batería: 41.86 kWh / 200 km y 53.58 kWh / 260 km"
    }
  ]'::jsonb,
  updated_at = now()
WHERE slug = 'kama-serie-es-esp';
